# Settings for Mojira Discord bot

owners:
  - '342589551618949121' # UserTeemu

filterFeeds:
  - jql: project = MC AND resolved > -1m AND resolution = Fixed AND fixVersion in unreleasedVersions()
    channel: '666349583227682819'
    publish: true
    interval: 30000
    filterFeedEmoji: '🎉'
    title: '{{num}} tickets have just been resolved as Fixed!'
    titleSingle: This ticket has just been resolved as Fixed!

versionFeeds:
    #java-fixes
  - projects:
      - MC
    channel: '666349583227682819'
    publish: true
    interval: 30000
    scope: 5
    versionFeedEmoji: '🎉'
    actions:
      - released
      - unreleased
      - renamed

    #version-log
  - projects:
      - BDS
      - MC
      - MCD
      - MCL
      - MCPE
      - REALMS
    channel: '741600360619049000'
    interval: 300000
    scope: 5
    actions:
      - created
      - archived
      - unarchived
      - released
      - unreleased
      - renamed
