# Settings template / documentation

# Whether or not the bot is in debug mode.
# Optional; false by default.
debug: <boolean>

# The directory to save logs to; false to disable saving log files.
# Optional; false by default.
logDirectory: <string | false>

# Your bot token used to log in to Discord with the bot.
token: <string>

# A list of user IDs for owner only commands.
# Optional; empty by default.
owners:
  - <string>
  - <string>
  - ...

# Whether the bot should send an embed when a full URL to a ticket gets posted.
ticketUrlsCauseEmbed: <boolean>

# Whether the bot should send an embed when a ticket gets posted inside of a quote.
quotedTicketsCauseEmbed: <boolean>

# A prefix that prevents the bot from posting an embed for a mentioned ticket.
# If this prefix is longer than 1, none of the characters can be used.
# When omitted or empty, no prefix prevents embeds.
forbiddenTicketPrefix: <string>

# Prefix that needs to preceed any mentioned ticket in order for the bot to post an embed
# If this prefix is longer than 1, the entire string needs to prefix any mentioned ticket.
# When omitted or empty, no prefix is required for posting embeds.
requiredTicketPrefix: <string>

# An emoji or emoji ID which, when reacted to a bot embed, deletes it.
embedDeletionEmoji: <string>

# The maximum number of results returned by the jira search command.
maxSearchResults: <number>

# The projects the bot should be able to find tickets for.
projects:
  - <string>
  - <string>
  - ...

# A list of feeds that should be sent when there are unknown tickets in a specific filter.
filterFeeds:
    # The filter's JQL query.
  - jql: <string>

    # The JQL query for which tickets should be allowed to be reposted that have been posted previously.
    # Optional; Only include if cached is set to true
    jqlRemoved: <string>

    # The ID of the channel in which the feed should be sent.
    channel: <string>

    # The interval of the check for this filter feed, in milliseconds.
    interval: <number>
    
    # The emoji to react to all filter feed messages with.
    # Optional; none by default.
    filterFeedEmoji: <string>

    # The title for this feed embed.
    # {{num}} will be replaced by the number of ticket(s).
    title: <string>
    
    # The message accompanying this feed embed, in case there's only one ticket.
    # If this is not set, `title` will be used instead.
    titleSingle: <string>

    # Whether the bot should automatically publish feed messages it posts, if the channel is an announcement channel.
    # Optional; false by default.
    publish: <boolean>

    # Whether the bot should cache tickets in the filter feed, 
    # If false, the property lastRun should be included in the jql, but when true, the filter feed will be less efficient.
    # Optional; true by default.
    cached: <boolean>
  
  - <see above>
  - ...

# A list of feeds that should be sent when there has been a change to a version.
versionFeeds:
    # The projects whose versions should be monitored.
  - projects:
      - <string>
      - <string>
      - ...

    # The ID of the channel in which the feed should be sent.
    channel: <string>

    # The interval of the check for this version feed, in milliseconds.
    interval: <number>

    # The emoji to react to all version feed messages with.
    # Optional; none by default.
    versionFeedEmoji: <string>

    # How many versions should be monitored; only the x latest versions are monitored.
    scope: <number>

    # A list of actions that should be included in the version feed.
    actions:
      - <'created' | 'released' | 'unreleased' | 'archived' | 'unarchived' | 'renamed'>
      - ...

    # Whether the bot should automatically publish feed messages it posts, if the channel is an announcement channel.
    # Optional; false by default.
    publish: <boolean>
  
  - <see above>
  - ...

# Configuration for postgres database for custom feeds
databaseConfig:
  - host: "<your postgres database host>"
  - port: <your postgres database port>
  - user: "<your postgres database username>"
  - password: "<your postgres database password>"
  - database: "<your postgres database name>"
  